[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "si_image_processing_lab"
readme = "README.md"
version = "0.1.0"
dependencies = [
    "ipython>=8.10",
    "jupyterlab>=3.0",
    "notebook",
    "kedro~=1.4.0",
    "pillow>=10.0.0",
    "kedro-datasets>=3.0.0",
]

[project.scripts]
si-image-processing-lab = "si_image_processing_lab.__main__:main"

[project.entry-points."kedro.hooks"]


[tool.setuptools.packages.find]
where = [
    "src",
]
namespaces = false

[tool.kedro]
package_name = "si_image_processing_lab"
project_name = "si-image-processing-lab"
kedro_init_version = "0.19.0"
tools = []
example_pipeline = "False"
source_dir = "src"

# =========================
# TESTING CONFIG (Pytest)
# =========================
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --cov=src --cov-report=term-missing"

# =========================
# CODE QUALITY (Ruff)
# =========================
[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = []
[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ruff (>=0.15.14,<0.16.0)"
]
